### ISSUE TITLE
How do you install this. I copied the files into multi-ldap but what do I need from There.

### ISSUE THREAD

**Issue by ivonpint** [philbertphotos/osticket-multildap-auth-plugin#73]

**Comment by ivonpint** [comment]
Well i guess i figured it out.
1. get the make.php from https://github.com/osTicket/osTicket-plugins
2. place the make.php in the root of the plugin folder and have the multi-ldap folder with all the files in it
3. run php -dphar.readonly=0 make.php build multi-ldap
4. You will see the plugin when you add a plugin

**Comment by philbertphotos** [comment]
That is interesting need to look at how they do that and include it in my instructions.
Thanks .

**Comment by ivonpint** [comment]
Great plugin BTW!  I got it installed but I cant seem to get it working. I'm missing something, somewhere.

![image](https://github.com/philbertphotos/osticket-multildap-auth-plugin/assets/132573837/1a97b38d-d413-4ad8-ab66-dec6c2cb2491)
![image](https://github.com/philbertphotos/osticket-multildap-auth-plugin/assets/132573837/244c65ac-0eb9-47c9-9ce6-4a94df79d789)
![image](https://github.com/philbertphotos/osticket-multildap-auth-plugin/assets/132573837/eddf1f17-cd39-4838-818c-1733e23f6216)

**Comment by philbertphotos** [comment]
You still have an issue?

**Comment by flimby1** [comment]
It's still necessary to make the phar file?
Because I tried it but in the apache error log I see this:
[php:error] [pid 25992:tid 1892] [client 10.26.64.53:59628] PHP Fatal error:  Uncaught Error: Failed opening required 'C:/xampp/htdocs/sito2/include/plugins/multi-ldap.phar/auth.php' (include_path='./;C:/xampp/htdocs/sito2/include/;C:/xampp/htdocs/sito2/include/pear/;phar://C:/xampp/htdocs/sito2/include/plugins/auth-ldap - Copia.phar/include') in C:\\xampp\\htdocs\\sito2\\scp\\sync_mldap.php:13\nStack trace:\n#0 {main}\n  thrown in C:\\xampp\\htdocs\\sito2\\scp\\sync_mldap.php on line 13, referer: http://server_host/sito2/scp/plugins.php?id=9&xid=13

**Comment by philbertphotos** [comment]
Never used the PHAR file. it may cause issues with sync_mldap.php since it needs to be copied to the SCP folder and I suspect that is why sync is failing.
I copy the files directly to the required folder.

**Comment by flimby1** [comment]
Ok so I use only to copy multi-ldap on the plugin folder.
But with this solution I don't see any message about syncronization. Did I need to add something on the cron file?
For your information I have installed the system on a Xampp with windows and using a task scheduler to launch the rcron.php file

**Comment by philbertphotos** [comment]
> Ok so I use only to copy multi-ldap on the plugin folder. It seems that I was able to see the user from the active directory but if I try to login I receive the error 49 for bad credentials

When you first installed the plugin it creates logs in the Osticket log section can you tell me what it says MLA-Copy or MLA-Updated.

If you recently updated to the new version it should say MLA-????

**Comment by flimby1** [comment]
Yes I find in the log the MLA-Updated

**Comment by philbertphotos** [comment]
OK did it fail or successful?
It would say MLA-Updated (failed) or MLA-Updated (success)
Include where it was trying to copy too.

**Comment by flimby1** [comment]
it says MLA-Updated (success) 
Here the message: Replacing file 'C:\xampp\htdocs\sito2\include\plugins\multi-ldap/sync_mldap.php' to SCP folder successful

**Comment by philbertphotos** [comment]
GREAT seems like it could be a problem, between lunix and windows paths

**Comment by philbertphotos** [comment]
This is the problem in line 13
require_once (INCLUDE_DIR . 'plugins/'.$_REQUEST['plugin'].'/auth.php');
Linux uses "/" but linux uses "\" I need to make compatible with both OS systems.

**Comment by philbertphotos** [comment]
Or its an incompatibility with PHAR file. I suggest that you dont use PHAR and see if the error goes away ... I am leaning more to that ync_mldap.php is looking for auth.php but its in a compressed PHAR file it cant read.

So delete the PHAR and copy the RAW files instead to the same folder should fix the issue I never designed it to work as a PHAR.

**Comment by flimby1** [comment]
the problem is still present, now I have a doubt, is the plugin compatible with the Active directory based on Windows 2012?

**Comment by philbertphotos** [comment]
> the problem is still present, now I have a doubt, is the plugin compatible with the Active directory based on Windows 2012? EDIT: ![image](https://user-images.githubusercontent.com/44726868/273858947-dedb7da5-56d7-4f46-80be-1a1dedbf2caf.png) In this image you can see the result of a search on the ldap if you need (I had to cenuse some part for privacy)

I use it with Windows 2012 so yes it works. The plugin is not compatible with phar format

**Comment by philbertphotos** [comment]
Finally FIXED
